#!/bin/bash
# Auto-generated link command with --defsym bridges
# Generated 2026-07-25

SDL3_LIB="/nix/store/mia8j67jl1jv7hg3xyx0cqrabp8mv2is-sdl3-3.4.10-lib/lib"

cd /home/user/projects/v43/jenrik/lego-loco-rev-eng/src/sdl3_shims && \
g++ -std=c++17 -fpermissive -Wl,--allow-multiple-definition \\
  build/main.o build/sdl3_ddraw.o build/sdl3_dsound.o build/sdl3_window.o \\
  ../decompiled_cpp/build/shared/stubs_impl.o ../decompiled_cpp/build/shared/link_stubs.o \\
  ../decompiled_cpp/build/core/*.o ../decompiled_cpp/build/game/*.o \\
  ../decompiled_cpp/build/graphics/*.o ../decompiled_cpp/build/audio/*.o \\
  ../decompiled_cpp/build/input/*.o ../decompiled_cpp/build/network/*.o \\
  ../decompiled_cpp/build/resources/*.o ../decompiled_cpp/build/town/*.o \\
  ../decompiled_cpp/build/ui/*.o ../decompiled_cpp/build/world/*.o \\
  ../decompiled_cpp/build/shared/Collection.o ../decompiled_cpp/build/shared/TimerSlotList.o \\
  -L${SDL3_LIB} -lSDL3 -lm \\
  -Wl,--defsym=ArrivalQueue_AddVehicle(void*, void*)=0 \\\
  -Wl,--defsym=ArrivalQueue_RemoveVehicle(void*, unsigned int, char)=0 \\\
  -Wl,--defsym=AssetMgr_LoadFile(void*, char const*, int*)=0 \\\
  -Wl,--defsym=AudioChannel_IsActive(int)=0 \\\
  -Wl,--defsym=AudioChannel_Pause=0 \\\
  -Wl,--defsym=AudioChannel_Play=0 \\\
  -Wl,--defsym=AudioChannel_Release(void*)=0 \\\
  -Wl,--defsym=Building::Building(int)=0 \\\
  -Wl,--defsym=Building_CheckPlacement(Building*, int, int)=0 \\\
  -Wl,--defsym=Building_RemoveOccupant(int*)=0 \\\
  -Wl,--defsym=ButtonSprite_Ctor=0 \\\
  -Wl,--defsym=CGWND_AudioChannel_Play(void*)=0 \\\
  -Wl,--defsym=CGWND_AudioChannel_Release(void*)=0 \\\
  -Wl,--defsym=CGWND_AudioChannel_Stop(void*)=0 \\\
  -Wl,--defsym=CGWND_AudioChannel_UpdatePosition(void*, int, int)=0 \\\
  -Wl,--defsym=CGWND::CGWND(void*)=0 \\\
  -Wl,--defsym=CGWND_CursorEditWindow_Ctor(void*, int, int)=0 \\\
  -Wl,--defsym=CGWND_InitAllSubsystems(void*)=0 \\\
  -Wl,--defsym=CGWND_InstallPathInit()=0 \\\
  -Wl,--defsym=CGWND_MapResourceToDirection(int)=0 \\\
  -Wl,--defsym=CGWND_PumpMessages(void*, unsigned char)=0 \\\
  -Wl,--defsym=CGWND_RegisterWindowClass(void*)=0 \\\
  -Wl,--defsym=CGWND_SetFullscreenMode(char)=0 \\\
  -Wl,--defsym=CGWND_SetMode=0 \\\
  -Wl,--defsym=CGWND_SetPause(void*, unsigned char)=0 \\\
  -Wl,--defsym=CGWND::ShowMainMenu()=0 \\\
  -Wl,--defsym=Collection::GetAt(int)=0 \\\
  -Wl,--defsym=Collection::Resize(int)=0 \\\
  -Wl,--defsym=Config_GetIniString=0 \\\
  -Wl,--defsym=Config_ReadInt(void*, char const*, char const*, char const*)=0 \\\
  -Wl,--defsym=CRT_exit(char const**, char const**)=0 \\\
  -Wl,--defsym=CRT_free_pattern(void*, int, int, void*)=0 \\\
  -Wl,--defsym=CRT_itoa(int, char*, int)=0 \\\
  -Wl,--defsym=CRT_localtime(unsigned int*)=0 \\\
  -Wl,--defsym=CRT_memset_pattern(void*, int, int, void*)=0 \\\
  -Wl,--defsym=CRT_toupper(int)=0 \\\
  -Wl,--defsym=Cursor_HandleWindowPaint(void*, int)=0 \\\
  -Wl,--defsym=Cursor::update_network_names()=0 \\\
  -Wl,--defsym=Cursor_WaitForBlit(void*)=0 \\\
  -Wl,--defsym=DDRAW_DestroyAudio()=0 \\\
  -Wl,--defsym=DDRAW_FileData_Dtor(void*)=0 \\\
  -Wl,--defsym=DDRAW_FreeClipper(void*)=0 \\\
  -Wl,--defsym=DDRAW_GetDsoundErrorString(int)=0 \\\
  -Wl,--defsym=DDRAW_GetSurface()=0 \\\
  -Wl,--defsym=DDRAW_Init()=0 \\\
  -Wl,--defsym=DDRAW_LoadFile(int*, char const*)=0 \\\
  -Wl,--defsym=DDRAW_PresentRect(void*, void*, int*, unsigned char)=0 \\\
  -Wl,--defsym=DDRAW_ReleaseSurfaces()=0 \\\
  -Wl,--defsym=DDRAW_RestoreSurfaces=0 \\\
  -Wl,--defsym=DDRAW_SelectBuilding(void*, void*)=0 \\\
  -Wl,--defsym=DDRAW_SetSurfaceFormat=0 \\\
  -Wl,--defsym=DDRAW_UnlockPrimary=0 \\\
  -Wl,--defsym=DirectPlay_constructor(void*)=0 \\\
  -Wl,--defsym=DPLAY_CleanupPlayer(void*)=0 \\\
  -Wl,--defsym=DPLAY_CreatePlayer(void*)=0 \\\
  -Wl,--defsym=DPLAY_SetPlayerData(void*, char const*)=0 \\\
  -Wl,--defsym=FormatResourceString=0 \\\
  -Wl,--defsym=GameAudio_PlayResourceEx(void*, unsigned int, int*)=0 \\\
  -Wl,--defsym=GameAudio_StopFinished(void*)=0 \\\
  -Wl,--defsym=GameAudio_UpdateVolume(void*, char)=0 \\\
  -Wl,--defsym=Game_CheckTimeInRange(int*, int*, int*)=0 \\\
  -Wl,--defsym=GameConfig_constructor(void*)=0 \\\
  -Wl,--defsym=GameObject_HitTest(void*, int, int)=0 \\\
  -Wl,--defsym=GameObject_SetFrame(void*, int, bool)=0 \\\
  -Wl,--defsym=GameObject_SetWorldPos(void*, int, int)=0 \\\
  -Wl,--defsym=GameSetupPanel::ConnectToNetworkGame(int)=0 \\\
  -Wl,--defsym=GameSetupPanel_drawGrid(void*)=0 \\\
  -Wl,--defsym=GameSetupPanel::HandleMapClick(int, int)=0 \\\
  -Wl,--defsym=GameSetupPanel_loadLayouts(void*, unsigned char)=0 \\\
  -Wl,--defsym=GameSetupPanel::SelectLayoutEntry(int)=0 \\\
  -Wl,--defsym=GameSetupPanel::SendScenarioSelect(int)=0 \\\
  -Wl,--defsym=GameSetupPanel_updateTitle(void*)=0 \\\
  -Wl,--defsym=GAMESTATE_ConnectToNetworkGame(void*)=0 \\\
  -Wl,--defsym=GAMESTATE_EditorState_Ctor(void*, char)=0 \\\
  -Wl,--defsym=GAMESTATE_EditorState_Detach(int)=0 \\\
  -Wl,--defsym=GAMESTATE_FindAdjacentTrack(void*)=0 \\\
  -Wl,--defsym=GAMESTATE_FindTrackPosition(void*, int, int)=0 \\\
  -Wl,--defsym=GAMESTATE_InitTrackAtPosition(void*, int, int)=0 \\\
  -Wl,--defsym=GameVehicle_RemoveDestination(void*, unsigned int, char)=0 \\\
  -Wl,--defsym=GameWindow_BaseDtor(void*)=0 \\\
  -Wl,--defsym=GameWindow_Create(void*, int, void*, int, int, int, int, void*, void*, unsigned int, int, int, unsigned char)=0 \\\
  -Wl,--defsym=GameWindow_Create(void*, int, void*, int, int, int, int, void*, void*, unsigned int, unsigned int, unsigned int, unsigned char)=0 \\\
  -Wl,--defsym=GameWindow_Hide(void*)=0 \\\
  -Wl,--defsym=GameWindow_SetPosition(void*, int, int)=0 \\\
  -Wl,--defsym=GameWindow_Show(void*)=0 \\\
  -Wl,--defsym=_g_cursor_back=0 \\\
  -Wl,--defsym=_g_cursor_refcount=0 \\\
  -Wl,--defsym=GetResourceType(int)=0 \\\
  -Wl,--defsym=g_OutputDebugStringA=0 \\\
  -Wl,--defsym=_g_primary_surface=0 \\\
  -Wl,--defsym=HelpWnd::render_page(int*)=0 \\\
  -Wl,--defsym=HelpWnd::render_scroll_down(int*)=0 \\\
  -Wl,--defsym=HelpWnd::render_scroll_up(int*)=0 \\\
  -Wl,--defsym=HelpWnd::update_anim_sprite(int)=0 \\\
  -Wl,--defsym=IDirectDrawSurface4::~IDirectDrawSurface4()=0 \\\
  -Wl,--defsym=IDirectDrawSurface4::IDirectDrawSurface4()=0 \\\
  -Wl,--defsym=__imp_SystemParametersInfoA=0 \\\
  -Wl,--defsym=INPUT_ExitGame(void*, int, int)=0 \\\
  -Wl,--defsym=INPUT_LoadConfig(void*)=0 \\\
  -Wl,--defsym=INPUT_NewWorld(int)=0 \\\
  -Wl,--defsym=INPUT_SetKeyboard(void*)=0 \\\
  -Wl,--defsym=INPUT_SetMouse(void*)=0 \\\
  -Wl,--defsym=InvalidateRect(void*, RECT const*, int)=0 \\\
  -Wl,--defsym=Math_DistSquared(int, int, int, int)=0 \\\
  -Wl,--defsym=NET_ComputeColor(unsigned char, unsigned char, unsigned char)=0 \\\
  -Wl,--defsym=NET_GetHostName(int, int)=0 \\\
  -Wl,--defsym=NETMAN_constructor(void*)=0 \\\
  -Wl,--defsym=NETMAN_FreePacket(int)=0 \\\
  -Wl,--defsym=NETMAN_Init(void*, unsigned char)=0 \\\
  -Wl,--defsym=NETMAN_ResetNetworkState(void*)=0 \\\
  -Wl,--defsym=NETMAN_SendAck(void*)=0 \\\
  -Wl,--defsym=NETMAN_SetGameMode(void*, int)=0 \\\
  -Wl,--defsym=NETMAN_StartClientSession(void*)=0 \\\
  -Wl,--defsym=NETMAN_StopSession(void*)=0 \\\
  -Wl,--defsym=Ordinal_1(int, void*)=0 \\\
  -Wl,--defsym=Ordinal_1(void*, void*, void*, void*)=0 \\\
  -Wl,--defsym=Ordinal_2(void*)=0 \\\
  -Wl,--defsym=Ordinal_4(void*, void**, void*, void*, void*)=0 \\\
  -Wl,--defsym=PixelDataCache_Ctor(void*)=0 \\\
  -Wl,--defsym=PlayerConfig_GetName(void*, char*, int)=0 \\\
  -Wl,--defsym=PlayerConfig_SaveToFile(void*)=0 \\\
  -Wl,--defsym=PlayerRecord_constructor(void*)=0 \\\
  -Wl,--defsym=PlaySound=0 \\\
  -Wl,--defsym=PlaySound(int)=0 \\\
  -Wl,--defsym=RESDATA_DtorBody(void*)=0 \\\
  -Wl,--defsym=RESDATA_GameVehicle_BaseDtor(void*)=0 \\\
  -Wl,--defsym=RESDATA_GameVehicle_Ctor(void*, int)=0 \\\
  -Wl,--defsym=RESDATA_IsBuildingTile=0 \\\
  -Wl,--defsym=RESDATA_IsRoadTile=0 \\\
  -Wl,--defsym=RESDATA_IsValidTrackIndex(void*, short)=0 \\\
  -Wl,--defsym=RESDATA_ScriptedObject_AddChild(void*, int, int)=0 \\\
  -Wl,--defsym=RESDATA_ScriptedObject::EnterBuildMode(unsigned char)=0 \\\
  -Wl,--defsym=RESDATA_UpdateChild(void*)=0 \\\
  -Wl,--defsym=RESMGR_AllocResourceEntry(ResourceEntry*, int, int)=0 \\\
  -Wl,--defsym=RESMGR_GetById(void*, unsigned int)=0 \\\
  -Wl,--defsym=RESMGR_LoadSoundResource=0 \\\
  -Wl,--defsym=RESMGR_ReleaseSoundResource=0 \\\
  -Wl,--defsym=RESMGR_RemoveResource(RESDATA*)=0 \\\
  -Wl,--defsym=ResourceManager_GetById=0 \\\
  -Wl,--defsym=ResourceManager_GetStringById(void*, unsigned int)=0 \\\
  -Wl,--defsym=ResourceManager_Init(void*)=0 \\\
  -Wl,--defsym=ResourceManager_Shutdown(int)=0 \\\
  -Wl,--defsym=SetRect(void*, int, int, int, int)=0 \\\
  -Wl,--defsym=SortedCollection::Compare(void*, void*)=0 \\\
  -Wl,--defsym=SortedCollection::SortRange(int, int)=0 \\\
  -Wl,--defsym=Sprite_Init=0 \\\
  -Wl,--defsym=Sprite_SetState=0 \\\
  -Wl,--defsym=TileMap_GetObjectAt(void*, short, short, short)=0 \\\
  -Wl,--defsym=TileMap_GetTileAt(void*, void*)=0 \\\
  -Wl,--defsym=TileMap_GetTileRect(void*, void*)=0 \\\
  -Wl,--defsym=TileMap_Init(void*, unsigned char)=0 \\\
  -Wl,--defsym=TileMap_InvalidateRect=0 \\\
  -Wl,--defsym=TileMap_SetViewport(void*, void*)=0 \\\
  -Wl,--defsym=TileMap_UpdateViewport(void*, void*, short)=0 \\\
  -Wl,--defsym=timeBeginPeriod(unsigned int)=0 \\\
  -Wl,--defsym=Town_BlitViewport(void*, int, int, int, int, int, int)=0 \\\
  -Wl,--defsym=Town_CheckOccupied(void*, int, int, int, int)=0 \\\
  -Wl,--defsym=Town_CopyTiles8bpp_Transparent(void*, int, int, int, int, int, int, int, int, int, int)=0 \\\
  -Wl,--defsym=Town_SelectBuilding(void*, void*)=0 \\\
  -Wl,--defsym=TrackPiece_Ctor(void*, int, int, unsigned short)=0 \\\
  -Wl,--defsym=TrackPiece_Dtor(void*)=0 \\\
  -Wl,--defsym=TrackPiece_SetZoom(void*, short)=0 \\\
  -Wl,--defsym=TrainEntity::TrainEntity(int)=0 \\\
  -Wl,--defsym=Train_QueueMessage(void*, void*)=0 \\\
  -Wl,--defsym=TrainStation_Ctor(void*, int, int)=0 \\\
  -Wl,--defsym=typeinfo for UI_WindowBase=0 \\\
  -Wl,--defsym=UI_ChildWindow_Dtor(void*)=0 \\\
  -Wl,--defsym=UI_ChildWindow_Render(void*, void*)=0 \\\
  -Wl,--defsym=UI_CreateChildWindow=0 \\\
  -Wl,--defsym=UI_CreateTooltip(void*, int, short, int, int)=0 \\\
  -Wl,--defsym=UI_DefWndProc(void*, unsigned int, unsigned int, int)=0 \\\
  -Wl,--defsym=UIEntity_Ctor=0 \\\
  -Wl,--defsym=UI_MainMenu_SetState(void*, int)=0 \\\
  -Wl,--defsym=UIPANEL_BeginPaint=0 \\\
  -Wl,--defsym=UIPANEL_Blit=0 \\\
  -Wl,--defsym=UIPANEL_BlitSurface(void*, int, int, void*, int, int)=0 \\\
  -Wl,--defsym=UIPANEL_Blit(void*, unsigned int, unsigned int, int, unsigned int, int**, unsigned int, unsigned int, int, unsigned int, unsigned int)=0 \\\
  -Wl,--defsym=UIPANEL_CopySurface(void*, int)=0 \\\
  -Wl,--defsym=UIPANEL_CreateSurface=0 \\\
  -Wl,--defsym=UIPANEL_EndPaintEx=0 \\\
  -Wl,--defsym=UIPANEL_EndPaint(void*)=0 \\\
  -Wl,--defsym=UIPANEL_StretchBlit(void*, char const*, int, int, int)=0 \\\
  -Wl,--defsym=UI_SetWindowVisible(void*, char)=0 \\\
  -Wl,--defsym=UI_WindowBase_BaseDtor=0 \\\
  -Wl,--defsym=UI_WindowBase_Ctor=0 \\\
  -Wl,--defsym=UI_WindowBase::~UI_WindowBase()=0 \\\
  -Wl,--defsym=UI_WindowBase::UI_WindowBase(void*, unsigned int)=0 \\\
  -Wl,--defsym=UpdateWindow(void*)=0 \\\
  -Wl,--defsym=Vehicle_Ctor(void*, int, int, char, char)=0 \\\
  -Wl,--defsym=Vehicle_DetachAll(int)=0 \\\
  -Wl,--defsym=VehicleEditor_BlitBackground(void*, int, int)=0 \\\
  -Wl,--defsym=VehicleEditor::CalcAngle()=0 \\\
  -Wl,--defsym=VehicleEditor::CheckEdgeBounds(void*)=0 \\\
  -Wl,--defsym=VehicleEditor_CheckEditBounds1=0 \\\
  -Wl,--defsym=VehicleEditor::CheckEditBounds1(void*)=0 \\\
  -Wl,--defsym=VehicleEditor::CheckEditBounds2(void*)=0 \\\
  -Wl,--defsym=VehicleEditor::CheckVehicleAttach(void*)=0 \\\
  -Wl,--defsym=VehicleEditor_GetResourceId(int)=0 \\\
  -Wl,--defsym=VehicleEditor_IsInBounds(void*, short, short, short)=0 \\\
  -Wl,--defsym=VehicleEditor_RemoveVehicle(void*, int)=0 \\\
  -Wl,--defsym=VehicleEditor_Update(void*)=0 \\\
  -Wl,--defsym=Vehicle_GetNearestTrack(int)=0 \\\
  -Wl,--defsym=Vehicle_GetOccupantCount(int)=0 \\\
  -Wl,--defsym=Vehicle_InitOccupant(void*, int)=0 \\\
  -Wl,--defsym=Vehicle_InitRoute(void*, int, unsigned int, char)=0 \\\
  -Wl,--defsym=Vehicle_IsMoving(void*)=0 \\\
  -Wl,--defsym=Vehicle_LoadSounds(void*, int*, char)=0 \\\
  -Wl,--defsym=Vehicle_Stop(void*, int, unsigned char)=0 \\\
  -Wl,--defsym=Vehicle_UpdatePosition(void*, char)=0 \\\
  -Wl,--defsym=vtable for Collection=0 \\\
  -Wl,--defsym=vtable for UIEntity=0 \\\
  -Wl,--defsym=WIN32_GetSystemMetrics(void*)=0 \\\
  -Wl,--defsym=WIN32_PostQuit()=0 \\\
  -Wl,--defsym=WIN32_RecvNetworkData(void*, unsigned int, char const*)=0 \\\
  -Wl,--defsym=WIN32_StreamDestroyImmediate(void*)=0 \\\
  -Wl,--defsym=WIN32_StreamDestroy(void*)=0 \\\
  -Wl,--defsym=WIN32_StreamOpen=0 \\\
  -Wl,--defsym=WIN32_StreamOpenFile=0 \\\
  -Wl,--defsym=WIN32_StreamOpenPath(void*, char const*, int, int)=0 \\\
  -Wl,--defsym=WIN32_StreamRead(void*, void*, int)=0 \\\
  -Wl,--defsym=WNDPROC_EnterCriticalSection=0 \\\
  -Wl,--defsym=WNDPROC_LeaveCriticalSection=0 \\\
  -Wl,--defsym=WNDPROC_StreamCleanup(void*)=0 \\\
  -Wl,--defsym=WNDPROC_StreamFromMemory=0 \\\
  -Wl,--defsym=World_CheckActive(void*)=0 \\
  -o build/lego_loco
